/-
Copyright (c) 2026 Xinze Li. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Xinze Li
-/

/-!
# `lake exe combarg-skeleton`

Emits a starter Lean script for a min-max contradiction that
plugs into `CombArg`.  The output is a self-contained
"hello world"-style template with `YourGMT.*` placeholder
identifiers that a downstream geometric formalization fills in.

## Usage

```
lake exe combarg-skeleton                # default N parameter ("N")
lake exe combarg-skeleton --N 4          # specialize to a numeric N
lake exe combarg-skeleton --module MyProof > MyProof.lean
```

The emitted script compiles against `CombArg` once the four
`YourGMT.*` identifiers are defined.
-/

/-- One-line usage banner printed on `--help` or unknown options. -/
private def usage : String :=
"Usage: lake exe combarg-skeleton [--N <expr>] [--module <name>] [--help]

Emits a starter Lean script for a min-max contradiction.

Options:
  --N <name>          Variable name for the near-criticality
                      parameter (default: \"N\").  Must be a valid
                      Lean identifier.
  --module <name>     Emit `namespace <name>` ... `end <name>`
                      around the body (default: no namespace).
  --help, -h          Show this message."

/-- Parsed command-line options. -/
private structure Opts where
  nExpr  : String := "N"
  module : Option String := none

private def parseArgs : List String → Except String Opts
  | []              => .ok {}
  | "--help" :: _   => .error usage
  | "-h"     :: _   => .error usage
  | "--N" :: e :: rest => do
      let o ← parseArgs rest
      pure { o with nExpr := e }
  | "--module" :: n :: rest => do
      let o ← parseArgs rest
      pure { o with module := some n }
  | arg :: _        => .error s!"unknown option `{arg}`\n\n{usage}"

private def emit (o : Opts) : String :=
  let nsOpen  := o.module.map (s!"namespace {·}\n\n") |>.getD ""
  let nsClose := o.module.map (s!"\n\nend {·}") |>.getD ""
s!"\
import CombArg
import YourGMT  -- replace with your geometric formalization

{nsOpen}\
/-!
Starter min-max contradiction generated by `lake exe combarg-skeleton`.

Replace the four `YourGMT.*` identifiers with concrete declarations
from your formalization:

* `YourGMT.SweepoutType`        — sweepout type
* `YourGMT.admissibleClass`     — admissible class
* `YourGMT.choose_N`            — pick `N` so 1/(4N) beats the contradiction window
* `YourGMT.localWitness_of_DLT` — formalization of the local replacement lemma
* `YourGMT.lift_sweepout`       — lift `f'` back to a sweepout in 𝒜
-/

theorem minmax_contradiction
    (Ω  : YourGMT.SweepoutType)
    (hΩ : Ω ∈ YourGMT.admissibleClass)
    (h_minmax : Ω.boundaryEnergy.sup = YourGMT.infMinmax) :
    False := by
  set f := Ω.boundaryEnergy
  set m₀ := sSup (Set.range f)
  obtain ⟨{o.nExpr}, hN_pos, hN_window⟩ := YourGMT.choose_N Ω
  -- Per-parameter local witness from the geometric replacement lemma.
  have witness :
      ∀ t : unitInterval, f t ≥ m₀ - 1 / ({o.nExpr} : ℝ) →
        CombArg.LocalWitness unitInterval f t (1 / (4 * ({o.nExpr} : ℝ))) :=
    fun t ht => YourGMT.localWitness_of_DLT Ω t ht hN_pos
  -- Combinatorial step (this library) → scalar sup reduction.
  obtain ⟨f', S, _, h_le, h_eq, h_sup⟩ :=
    CombArg.exists_sup_reduction
      Ω.boundaryEnergyContinuous rfl hN_pos witness
  -- Geometric lift back to a sweepout in admissibleClass.
  obtain ⟨Ω', hΩ', hΩ'_energy⟩ :=
    YourGMT.lift_sweepout f' h_le h_eq Ω hΩ
  -- Contradiction with the inf-sup characterization of m₀.
  have h_lt : Ω'.boundaryEnergy.sup < m₀ := by
    rw [hΩ'_energy]; linarith [h_sup, hN_window]
  exact absurd h_lt (YourGMT.le_of_admissible hΩ' h_minmax)\
{nsClose}
"

def main (args : List String) : IO UInt32 := do
  match parseArgs args with
  | .ok opts =>
    IO.println (emit opts)
    return 0
  | .error msg =>
    IO.eprintln msg
    return 1
